### ISSUE TITLE
Cleanup supported platforms

### ISSUE THREAD

**Issue by rveznaver** [mdsol/mesos_cookbook#106]
As of Mesos 0.23.0, packages for several platforms are not built anymore (see: [downloads](http://open.mesosphere.com/downloads/mesos/#apache-mesos-0.23.0)). Are we ok with changing the platform list?
The new one is:
- Ubuntu 15.04
- Ubuntu 14.04
- Ubuntu 12.04
- Debian 8
- CentOS 7
- CentOS 6

**Comment by rayrod2030** [comment]
Sounds good to me.
