### ISSUE TITLE
--advertise_ip and --advertise_port not in Mesos 0.23

### ISSUE THREAD

**Issue by dimfeld** [mdsol/mesos_cookbook#107]
I don't see the above options in Mesos 0.23, either in the docs or when trying to run a Mesos master with those options. They are present in the master branch and 0.24-RC1 tag though, so should be coming soon.

**Comment by rayrod2030** [comment]
I must have pulled the latest flags from the Apache Mesos docs on the website without realizing that those flags are for the latest builds instead of for 0.23.0.  Will have to review all flags again.  Thanks for catching this!

**Comment by dimfeld** [comment]
Yeah, it's a bit confusing... I still haven't been able to actually find the 0.23 documentation aside from looking in the relevant branch in the Mesos git repo :)

**Comment by rayrod2030** [comment]
Might have to go back to what I was doing a while ago in just running the
binaries with --help.  Not ideal though.

**Comment by rveznaver** [comment]
Hi @dimfeld,
You can try out the new master branch which should support all options.

**Comment by rveznaver** [comment]
Should be fixed in 3.5.0.
