### ISSUE TITLE
Can't Install Repo on AWS linux 2015.09

### ISSUE THREAD

**Issue by lancehudson** [mdsol/mesos_cookbook#112]
I get `remote_file has an empty source` @ https://github.com/mdsol/mesos_cookbook/blob/master/recipes/repo.rb#L38

on AWS Linux 2015.09 the platform version according to ohai is `2015.09`

**Comment by rveznaver** [comment]
@lancehudson do you know how the versions of AWS Linux map to RHEL/CentOS releases?

**Comment by lancehudson** [comment]
I believe they are 6.x. I know they are not 7 yet. Its a moving target. 
https://forums.aws.amazon.com/message.jspa?messageID=504160

But I know you can test for the platform 'amazon'

**Comment by rveznaver** [comment]
The link you've posted seems quite old, is it still valid?
Also, I can't seem to find a way to test Amazon Linux using Kitchen with the Vagrant provider. What do you use for testing? Do you have a source for Amazon Linux vagrant images?

**Comment by lancehudson** [comment]
The link is ongoing with updates last year. As far as I can tell the info is true.

No Amazon linux is not available outside aws. you would need to use vagrant with ec2 as the backend and the amazon linux ami.

**Comment by rveznaver** [comment]
Hi @lancehudson, please try out the new master branch. Thanks!

**Comment by rveznaver** [comment]
Version 3.5.1 released with fixed Amazon Linux support, please reopen the issue if persisting. Thanks!
