### ISSUE TITLE
Please add Robert Vežnaver (rveznaver) as repo commiter

### ISSUE THREAD

**Issue by rayrod2030** [mdsol/mesos_cookbook#116]
Hey @harryw hope things are going well with you.  Can you please add @rveznaver as a project committer to all the Medidata Mesos related cookbooks (Mesos, Marathon and Chronos)?  I have been working with him for a while on these cookbooks and I trust him to help with reviewing and merging pull requests as well as handling releases and cookbook updates.  Cheers mate!

**Comment by harryw** [comment]
This should be taken care of - @rveznaver should have an invitation to the relevant team. Let me know if not!

**Comment by rveznaver** [comment]
@harryw I have permissions to the Mesos cookbook, thanks! However, I don't seem to have permissions to the Marathon cookbook.

**Comment by rayrod2030** [comment]
Thanks so much @harryw!

**Comment by harryw** [comment]
Sorry @rveznaver I did not read that properly. I'll add you to those too.

**Comment by rveznaver** [comment]
Thanks @harryw!
