### ISSUE TITLE
mesos master install fails centos7

### ISSUE THREAD

**Issue by aktarali** [mdsol/mesos_cookbook#129]
Hi Guys;

Would really appreciate some help here. The first chef-client run fails with the following message, 2nd time chef-client is run, everything works fine.
  -------------
  undefined method `find' for nil:NilClass
  
  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/mesos/recipes/install.rb:60:in `from_file'
    /var/chef/cache/cookbooks/mesos/recipes/master.rb:24:in `from_file'
    /var/chef/cache/cookbooks/wrapper/recipes/mesos_master.rb:2:in `from_file'
  
  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/mesos/recipes/install.rb:
  
   53:    end
   54:  
   55:    # refresh Yum cache before querying
   56:    Chef::Provider::Package::Yum::YumCache.instance.refresh
   57:    # get the version-release string directly from the Yum provider rpmdb
   58:    rpm_version = Chef::Provider::Package::Yum::YumCache.instance
   59:                  .instance_variable_get('@rpmdb').lookup('mesos')
   60>>                 .find { |pkg| pkg.version.v == node['mesos']['version'] }
   61:                  .version.to_s
   62:  
   63:    yum_package 'mesos' do
   64:      version rpm_version
   65:      not_if { ::File.exist? '/usr/local/sbin/mesos-master' }
   66:    end
   67:  end
   68:  
   69:  #
  
  
  Running handlers:
  Running handlers complete
  Chef Client failed. 3 resources updated in 10 seconds

**Comment by rveznaver** [comment]
Hi @aktarali,
It seems to me you are not running the latest version of the cookbook. Could you please check that you are running 3.5.1?

**Comment by rveznaver** [comment]
Closing after two months.
