### ISSUE TITLE
Mesos package install fails on Ubuntu 16.04 LTS (Xenial Xerus) due to missing APT repository

### ISSUE THREAD

**Issue by elijah** [mdsol/mesos_cookbook#134]
Annoying to track down.

Switching to wily-testing seems to make mesos install on xenial hosts, though I have not yet figured out whether it 'breaks' anything by using the older packages.

**Comment by elijah** [comment]
I understand that this is supposed to be fixed soon, at which point things should start to work with no further effort on the part of the mesos cookbooks.

**Comment by rveznaver** [comment]
AFAIK Mesosphere has not published packages for Ubuntu 16.04 LTS (Xenial Xerus). You could set ```
default['mesos']['repo'] = false``` in a wrapper cookbook and create your own recipe for installing the packages you need.

**Comment by bai** [comment]
This one is not relevant anymore and can be closed. Mesosphere published `xenial` packages and it just works(TM) now.
