### ISSUE TITLE
Mesos latest version 1.0.0.

### ISSUE THREAD

**Issue by raju-divakaran** [mdsol/mesos_cookbook#137]
Hello,

With the latest version of mesos, which is 1.0.0 its failing. 

As in the latest version work_dir flag is mandatory, during the validation step in the cookbook by executing /usr/sbin/mesos-slave --help it throws a message saying 

Flag 'work_dir' is required, but it was not provided

This makes the chef to fail. Can we please tweak the slave recipe so that it passes the default work_dir as well. 

Thanks

**Comment by raju-divakaran** [comment]
I just saw that, there is already a clean pull request to be merged

https://github.com/mdsol/mesos_cookbook/pull/136

**Comment by rayrod2030** [comment]
Just merged https://github.com/mdsol/mesos_cookbook/pull/136

**Comment by raju-divakaran** [comment]
Sorry its not working, do we need a version increase !?

**Comment by rayrod2030** [comment]
Yes you need to pull from master for now using berkshelf.  Will try to
publish some time this week.

**Comment by rveznaver** [comment]
@rayrod2030 We're still missing kitchen tests for 1.0.0 :(

**Comment by raju-divakaran** [comment]
@rayrod2030 It would be nice if you could find some time today, to publish the fix with a version upgrade. Thanks

**Comment by raju-divakaran** [comment]
I have reverted to use old mesos version! :(

**Comment by raju-divakaran** [comment]
Can we have a version increase for this cookbook ?

**Comment by rossbannerman** [comment]
I think this needs a metadata version bump.

**Comment by rveznaver** [comment]
@raju-divakaran and @rossbannerman: You may both use the master branch of this cookbook and get all the new features/bugfixes directly.

**Comment by raju-divakaran** [comment]
@rveznaver Can we enforce to download the master branch ? I tried to download the cookbook using

knife supermarlet download mesos 

It gets the version 3.5.1 without the change in slave.rb. Same is happening while we do a chef-client on the nodes that depends.

**Comment by rveznaver** [comment]
@raju-divakaran 
- docs if using berks: http://berkshelf.com
- docs for manual cookbook upload: https://docs.chef.io/knife_cookbook.html#upload
