### ISSUE TITLE
mesos rpm packages don't get installed on RedHat servers.

### ISSUE THREAD

**Issue by orasul** [mdsol/mesos_cookbook#37]
On RedHat server node['platform'] is 'redhat'
And node['platform_family'] is 'rhel'.

In mesos_cookbook / recipes / install.rb line 58 should be:
+when 'redhat', 'centos', 'amazon', 'scientific'
instead of:
-when 'rhel', 'centos', 'amazon', 'scientific'

**Comment by rayrod2030** [comment]
Addressed in PR https://github.com/mdsol/mesos_cookbook/pull/50

**Comment by rayrod2030** [comment]
Verified this is still a valid bug.  Submitting a fix in a few.

**Comment by rayrod2030** [comment]
This should be fixed by PR https://github.com/mdsol/mesos_cookbook/pull/51.  Changes are in the develop branch until we cut a release and push to the supermercado.

**Comment by brokensandals** [comment]
I tried the develop branch on red hat today. The change in pr 51 is not enough to fix this; as mentioned in the initial comment, 'rhel' also needs to change to 'redhat' in the `case distro` block of install.rb

**Comment by rayrod2030** [comment]
@brokensandals Thanks for the feedback.  I'm working on adding rpm repository support as I write this so I will try to fix the `case distro` issue in that same PR.

**Comment by rayrod2030** [comment]
@brokensandals I was able to get Redhat 6.4 to converge and pass all tests with PR https://github.com/mdsol/mesos_cookbook/pull/65.  Hopefully this gets us going in the right direction in regards to better Redhat support.

**Comment by brokensandals** [comment]
@rayrod2030 Awesome! It seems to be working for me.

**Comment by rayrod2030** [comment]
@brokensandals Ah great!  I'll close this issue for now but would love feedback if you run into any other issues as RHEL isn't my primary platform.  Thanks!
