### ISSUE TITLE
Replace Ubuntu 13.04 platform with Ubuntu 14.04

### ISSUE THREAD

**Issue by rayrod2030** [mdsol/mesos_cookbook#47]
Ubuntu 13.04 and 13.10 reached end of life in 2014.  We should update our tested platforms to Ubuntu 14.04.  This may require updates to the cookbook to be able to located the correct mesosphere hosted debian package.

**Comment by rayrod2030** [comment]
Addressed in PR https://github.com/mdsol/mesos_cookbook/pull/50

Note: 13.04 is now EOL so instead of discarding it as a supported platform altogether I upgraded it to 13.10 as one of the Ubuntu platforms that is supported.

**Comment by mjcdiggity** [comment]
PR #50 merged, closing issue.
