### ISSUE TITLE
Add support for building mesos from source

### ISSUE THREAD

**Issue by rayrod2030** [mdsol/mesos_cookbook#71]
It would be great to be able to build and install mesos from source.  This feature should support the following:

### Build Options
* --enable-shared[=PKGS]
* --enable-static[=PKGS]
* --enable-fast-install[=PKGS]
* --disable-libtool-lock
* --disable-java
* --disable-python
* --enable-debug
* --enable-optimize
* --disable-bundled
* --disable-bundled-distribute
* --disable-bundled-pip
* --disable-bundled-wheel
* --disable-python-dependency-install

### Configuration Options
* --with-gnu-ld
* --with-sysroot=DIR
* --with-zookeeper[=DIR]
* --with-leveldb[=DIR]	
* --with-glog[=DIR]
* --with-protobuf[=DIR]
* --with-gmock[=DIR]
* --with-curl=[=DIR]
* --with-sasl=[=DIR]
* --with-zlib=[=DIR]
* --with-apr=[=DIR]
* --with-svn=[=DIR]
* --with-network-isolator

**Comment by rveznaver** [comment]
Although possible, I would highly discourage such an approach for a Chef cookbook as it may result in different packages across nodes, therefore going against one of the core principals of chef (idempotence). The best practice is to use a CI tool (like Jenkins) to build the artifact, and then deploy it via Chef.

**Comment by rayrod2030** [comment]
You bring up a valid point but you should be able to reliably reproduce a mesos source build at a specific version by pulling the source from zip files up on github.  See:  https://github.com/apache/mesos/archive/0.21.1.zip.

This is a pretty low priority issue since I agree installing pre-compiled binaries and packages is a much better way to install Mesos.
