### ISSUE TITLE
Add support for installing Mesos from pre-built binary

### ISSUE THREAD

**Issue by rayrod2030** [mdsol/mesos_cookbook#72]
Some people like to create their own builds of Mesos with specific flags enabled.  This feature would allow users to install pre-built Mesos binaries to an install directory and to run that binary under some kind of process supervisor such as upstart, runit, sysv init, systemd etc..

**Comment by rveznaver** [comment]
@rayrod2030, I think you can close this one, unless you had something else in mind?

**Comment by rayrod2030** [comment]
Yup this is now satisfied via https://github.com/mdsol/mesos_cookbook/issues/76.  Thanks!
