### ISSUE TITLE
Ensure required flags are properly set for Mesos Master

### ISSUE THREAD

**Issue by rayrod2030** [mdsol/mesos_cookbook#84]
The cookbook should be proactive in warning when the following required master flags are missing:

* quorum
* work_dir

Currently if these flags are not set you will typically see mesos masters fail silently with little information as to the cause of the startup error.

**Comment by rveznaver** [comment]
Note: the 'zk' is not required if master is run in standalone mode (non-HA).

**Comment by rayrod2030** [comment]
Good point!

**Comment by rveznaver** [comment]
Note: 'quorum' is also not required if master is run in standalone mode :)
