### ISSUE TITLE
Add support for Centos/RHEL 7

### ISSUE THREAD

**Issue by rayrod2030** [mdsol/mesos_cookbook#85]
This will require adding systemd init support as well as additional test platforms.

**Comment by rveznaver** [comment]
Do you think it would also be good to add support for RHEL in the metadata.rb?

**Comment by rveznaver** [comment]
@rayrod2030, I think you can close this one.

**Comment by ovaistariq** [comment]
The change introduced in the PR, will cause it to fail on CentOS/RHEL version < 7. CentOS 6 does not use upstart, it uses sysvinit. Is CentOS 6 a supported platform, looking at metadata.rb does say it is supported.
