### ISSUE TITLE
Suggestion: remove compile time workarounds (+ dependency on chef-sugar)

### ISSUE THREAD

**Issue by rveznaver** [mdsol/mesos_cookbook#87]
As far as I could see, the only reason there is a dependency on chef-sugar are the "compile_time" options. These are here because the yum package provider is not smart enough to regex the version.
I suggest we remove setting up things in compile time and create an attribute for the package version. The trade-off between not having an automatic package version finder and removing compile time workarounds is probably worth it. Comments?

**Comment by rayrod2030** [comment]
Hey @rveznaver will try to get to all of this during the weekend.  Started a new job this week so it's been really busy for me.  Touch base soon!

**Comment by rveznaver** [comment]
Sounds good. The only issue I see here is...

![nobeer](http://i.imgur.com/vGzFZ3Sm.jpg)

**Comment by rayrod2030** [comment]
:beers: Cheers!

**Comment by rayrod2030** [comment]
Hey @rveznaver I think this idea is making more sense based on some recent issues with chef-sugar compile time compatibility.  Let me have a look at it today.

**Comment by rayrod2030** [comment]
My concern here is that package version names often change outside of major Mesos release announcements so I'm not sure how we would keep the full package names up to date via attributes.  Any thoughts on that?  Should the onus be on the cookbook user to make sure they are configuring with the right package name?
