### ISSUE TITLE
Configuring package location

### ISSUE THREAD

**Issue by jonnywri** [mdsol/mesos_cookbook#97]
I wanted to start a discussion before I submitted a pull request.  I have the distinct pleasure of working in an environment where access to external repositories for artifacts is hard to come by.  In this case, the cookbook is referencing the mesos rpm from the mesosphere repository.  I wanted to look at ways I might allow this attribute to be configured and thought I'd reach out and see which mechanism might work best.

Option 1: Allow configuration directly to the .rpm file.  My hesitations for this would be that it add unnecessary cruft to your configuration in order to support multiple linux distributions in a single configuration (maybe I shouldn't be so worried about this).

Option 2: Allow configuration of a base repository.  My hesitations with this plan would be that your repository would be expected to mirror the same paths as the mesosphere repository.

I'm open to other ideas as well, was just hoping I might be able to get some conversation started.

**Comment by rayrod2030** [comment]
@jonnywri Totally understand the need here and as you can tell this cookbook has always leaned towards installing the mesosphere packages which are not reachable or even desirable in some environments.  I would certainly welcome a pull request here or any suggestions.

**Comment by rveznaver** [comment]
@jonnywri If you'd like to use your own rpm, then simply set ```node['mesos']['repo']``` to false and use a wrapper cookbook with your own yum repo. The cookbook will then install the 'mesos' package from that repo (we simply mirror the mesosphere repo internally).

**Comment by rveznaver** [comment]
Hi @jonnywri, have you found the solution to your problem? Would like to close this issue as it seems to be solvable by using a wrapper cookbook.
