### ISSUE TITLE
Support Mesos 0.23.0

### ISSUE THREAD

**Issue by TheSerapher** [mdsol/mesos_cookbook#99]
Would be great to get support added for this version.

**Comment by tubit** [comment]
+1

**Comment by ankurcha** [comment]
+1

**Comment by yadavshubhanshu** [comment]
+1

**Comment by sample** [comment]
+1

**Comment by ankurcha** [comment]
I was at mesoscon 2015 and in one of the announcements it was presented that the release cycle of mesos will now be release a lot more often. Could we consider removing this requirement to manually update the `mesos_options.rb` file and use something that allows for easier upgrades. - something like a `node['mesos']['verify_options'] = false` mode.

**Comment by TheSerapher** [comment]
That may be a good option @ankurcha. With more frequent releases, this may become a large overhead to maintain all options in the cookbook to ensure the user sets them properly. Maybe this should just be left to the user instead.

**Comment by rayrod2030** [comment]
Release https://github.com/mdsol/mesos_cookbook/releases/tag/3.4.0

Thanks everyone for your patience.  I have been very busy and there were some issues getting all the tests to pass against Debian.  Will still need to put out a patch release to support Debian 8 for Mesos 0.23.0.
